// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoD8gCvAky6BLEDu3XB8PGOMnFoEcXCc',
    appId: '1:894397665890:web:d5350678ef4a02427cf73b',
    messagingSenderId: '894397665890',
    projectId: 'positive-thinker-a76ae',
    authDomain: 'positive-thinker-a76ae.firebaseapp.com',
    storageBucket: 'positive-thinker-a76ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJvQ5EPAUD_DQP62_hhghcVE50WR5--Y',
    appId: '1:894397665890:android:4953aa29554244077cf73b',
    messagingSenderId: '894397665890',
    projectId: 'positive-thinker-a76ae',
    storageBucket: 'positive-thinker-a76ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlMceFFhIbk9rtnI8O1T5VQ2xgm-6Nyx4',
    appId: '1:894397665890:ios:fc8d7b156f34afc77cf73b',
    messagingSenderId: '894397665890',
    projectId: 'positive-thinker-a76ae',
    storageBucket: 'positive-thinker-a76ae.firebasestorage.app',
    iosBundleId: 'com.octo.positivethinker',
  );
}
